### PR TITLE
Patch promise constructor fix

### LINKED ISSUE #24: Angular 19 ZoneAwarePromise error
I have successfully used friendlyCaptcha v1 (friendly-challenge package), when trying to upgrade to v2 using the upgrade guide (https://developer.friendlycaptcha.com/docs/v2/guides/upgrading-from-v1/javascript-api) I am getting the following error:

```
main.ts:5 ERROR TypeError: Class constructor ZoneAwarePromise cannot be invoked without 'new'
    at new fcPatch (sdk.js:835:70)
    at ZoneAwarePromise.then (zone.js:2727:38)
    at _ApplicationInitStatus.runInitializers (core.mjs:22356:36)
    at core.mjs:34729:18
    at _callAndReportToErrorHandler (core.mjs:22488:20)
    at core.mjs:34727:12
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:6495:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at ZoneImpl.run (zone.js:111:43)
```

I am using Angular 19.

### PR DESCRIPTION
**Pull request by gzuidhof**
Fixes #24.

Still putting it through its paces a bit to ensure this doesn't have unwanted side effects.

### CODE REVIEW

File: src/signals/collectStacktrace.ts [hunk 1]
```diff
@@ -133,13 +133,21 @@ export const takeRecords = (function () {
       };
       queue.push(record);
 
+      const v = (hasGetterOrSetter ? descriptor.get : descriptor.value);
+
+      // Promises are special as we are patching a constructor. This was added to support zone.js better (used inside
+      // of Angular).
+      if (c === prop) {
+        return v
+      }
```
Comment (greenberga) [inline src/signals/collectStacktrace.ts:142]: Do you think it could be risky to set a precedent of including specific fixes for different 3rd-party tools like Angular? Right now we have just this one, and perhaps it will stay like this, but I could envision a worst-case scenario where this file fills up with lots of different code paths for handling various different frameworks and libraries. We all know how the JavaScript ecosystem moves.

And in this case, it seems like Angular is moving away from these zones anyway. If the recommendation of the maintainers themselves is based on import order, maybe it's not so bad to follow that same pattern?

I don't have a strong feeling about this, though—just some rambly food for thought.

Would it make sense to also constrain this patch to `w.Promise[p]` by checking the `name` or `target` argument?

**Review by greenberga — APPROVED** [review]

File: src/signals/collectStacktrace.ts (hunk 1 above)
Comment (gzuidhof) [reply src/signals/collectStacktrace.ts:142]: I think we should be careful with fixes that are done for a particular framework - so I definitely agree with that.

In this case I think the fix doesn't hurt to have for non-Angular users too (it's possible other libaries will also overwrite the constructor). Angular is a pretty big library too (even if moving away from this feature.. some codebases are likely stuck in the past) - so in this case I think it makes sense.

Right now it is constrained to `window.Promise.constructor` because that's the only constructor we patch, which I think is not going to change for the foreseeable future.

Comment (gzuidhof) [reply src/signals/collectStacktrace.ts:142]: I'll add a comment to remind us if we add new constructor patches
